### PR TITLE
Update some requirements and make them less restrictive

### PR DESCRIPTION
**Pull request by niallcm**
## Description
Libraries should not pin exact versions of requirements as it often makes them incompatible with other libraries.

There is a clear demand for this change as evidenced by the related issues and PRs.

This package's excessively restrictive requirements have become a pain point and if not addressed will force users to consider competitor services for improved security and developer experience.

## Related Issue
https://github.com/adobe/pdfservices-python-sdk/issues/15
https://github.com/adobe/pdfservices-python-sdk/pull/30
https://github.com/adobe/pdfservices-python-sdk/pull/25

## Tasks

- [x] I have signed the [CLA](http://adobe.github.io/cla.html).
- [x] I have written tests and verified that they fail without my change.

### CODE REVIEW

**Comment by niallcm** [comment]
In case anyone sees this and is curious, I tried about a week ago to contact the published email from pypi/setup.py, and have also reported this today on the [PDF Services developer forum](https://community.adobe.com/t5/acrobat-services-api-discussions/pdfservices-python-sdk-has-frozen-dependencies/m-p/14450995#M8103).

Neither of these has yet elicited a response.

**Comment by niallcm** [comment]
@vardhi @paras-n I see you are actively involved in the development of this library as you've reviewed/merged another PR in this repo today.

Are you able to give us any indication if there's likely to be any movement on this?

I'd like to know whether I or not I should give up hope and start working on replacing the extract API with a competitor service.

**Comment by niallcm** [comment]
Updating these dependencies is important for developer experience but also from a security perspective, as e.g. the frozen `cryptography` dependency from **_2021_** [has a variety of known security issues](https://security.snyk.io/package/pip/cryptography/3.4.6).

**Comment by vardhi** [comment]
> @vardhi @paras-n I see you are actively involved in the development of this library as you've reviewed/merged another PR in this repo today.
> 
> Are you able to give us any indication if there's likely to be any movement on this?
> 
> I'd like to know whether or not I should give up hope and start working on replacing the extract API with a competitor service.

Thanks, @niallcm the suggested changes in the repo were already noted and will be addressed in the next patch release.

**Comment by ToygunKarabas** [comment]
Adobe PDF services API is such a great tool for aAI applications but there are a lot of strict dependencies. It makes dependency conflicts easily. For example, langchain-core uses packaging library version of 23.2 but this is restricted with 21.3. If possible, can you loosen this dependency?

**Pull request closed without merging**
